# Generated by Django 4.2.1 on 2023-06-12 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0004_contact_alter_document_file'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
