# Generated by Django 4.2.1 on 2023-06-13 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0008_file_remove_uploadedfile_file_uploadedfile_files'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadedfile',
            name='files',
        ),
        migrations.DeleteModel(
            name='File',
        ),
        migrations.DeleteModel(
            name='UploadedFile',
        ),
    ]
