# Generated by Django 4.2.1 on 2023-06-13 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0010_resume'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Resume',
        ),
    ]
