# Generated by Django 4.2.1 on 2023-06-14 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0011_delete_resume'),
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('contact', models.CharField(max_length=20)),
                ('contact_information', models.TextField()),
                ('resume_objective', models.TextField()),
                ('education', models.TextField()),
                ('experience', models.TextField()),
                ('extracurricular_activities', models.TextField()),
                ('skills', models.TextField()),
                ('hobbies_and_interests', models.TextField()),
                ('additional_sections', models.TextField()),
            ],
        ),
    ]
