# Generated by Django 4.2.1 on 2023-06-18 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0014_remove_product_name_product_product_id_product_tags_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='static\\img\\products'),
        ),
    ]
